- name: Docker install
  hosts: docker
  roles:
    - geerlingguy.docker #https://github.com/geerlingguy/ansible-role-docker/blob/7.4.5/defaults/main.yml
  vars:
    docker_install_compose: true
  tasks:
    - name: Check dockge
      community.docker.docker_container_info:
        name: dockge
      register: dockgeinfo

    - name: Install dockge
      when: "not dockgeinfo.exists"
      block:
        - name: Add Stacks directory
          ansible.builtin.file:
            path: /opt/stacks
            state: directory

        - name: Add dockge install directory
          ansible.builtin.file:
            path: /opt/dockge
            state: directory

        - name: Install Dockge Compose File
          ansible.builtin.copy:
            src: dockge/docker-compose.yaml
            dest: /opt/dockge/docker-compose.yaml

        - name: Run dockge
          community.docker.docker_compose_v2:
            project_src: /opt/dockge
