---
- name: Grafana Install
  hosts: metrics
  roles:
    - role: grafana.grafana.grafana
    - role: prometheus.prometheus.prometheus
  tasks:
    # Hello world!

# Setup metrics here too
- name: Setup metrics
  ansible.builtin.import_playbook: "metrics.install.yaml"
