---
- name: Manage Komodo Periphery Service
  hosts: komodo_host
  roles:
    - sysupgrade
    - geerlingguy.docker

  tasks:
    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Run role
      ansible.builtin.include_role:
        name: bpbradley.komodo
      vars:
        komodo_action: "install"
        komodo_version: "core"
        enable_server_management: true
        komodo_core_url: "{{ komodo_api_url }}"
        komodo_core_api_key: "{{ komodo_api_key }}"
        komodo_core_api_secret: "{{ komodo_api_secret }}"
        komodo_passkeys:
          - "{{ komodo_core_passkey }}"
