---
- name: Manage Komodo Periphery Service
  hosts: komodo
  roles:
    - sysupgrade
    # - geerlingguy.docker

  tasks:
    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Run role
      ansible.builtin.include_role:
        name: bpbradley.komodo
      vars:
        komodo_action: "install"
        komodo_version: "latest"
