---
- name: Traefik install
  hosts: traefik
  vars:
    traefik_version: "3.4.0"
    pocketid_version: "1.7.0"
    # TODO: find a way to find these better
    # ansible_architecture: x86_64
    # ansible_system: Linux
    app_dist: "linux"
    app_arch: "amd64"
    traefik_archive: "traefik_v{{ traefik_version }}_{{ app_dist }}_{{ app_arch }}.tar.gz"
  tasks:
    - name: Install Traefik Binary
      ansible.builtin.unarchive:
        src: "https://github.com/traefik/traefik/releases/download/v{{ traefik_version }}/{{ traefik_archive }}"
        dest: "/usr/local/bin"
        mode: "755"
        remote_src: true
        include:
          - "traefik"
      notify: Restart Traefik

    - name: Install Pocket ID Binary
      ansible.builtin.get_url:
        url: "https://github.com/pocket-id/pocket-id/releases/download/v{{ pocketid_version }}/pocket-id-{{ app_dist }}-{{ app_arch }}"
        dest: "/usr/local/bin/pocketid"
        mode: "755"
      notify: Restart Pocket ID

    - name: Create Traefik Config Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "755"
      loop:
        - /etc/traefik
        - /etc/traefik/conf.d
        - /etc/traefik/ssl
        - /etc/pocketid
        - /etc/pocketid/data

    - name: Install Traefik Service File
      ansible.builtin.template:
        src: files/traefik/traefik.service.j2
        dest: /etc/systemd/system/traefik.service
        mode: "644"
      notify: Restart Traefik

    - name: Install Pocket ID Service File
      ansible.builtin.template:
        src: files/traefik/pocketid.service.j2
        dest: /etc/systemd/system/pocketid.service
        mode: "644"
      notify: Restart Pocket ID

    - name: Include Serivce Varaibles
      ansible.builtin.include_vars:
        file: services.index.yaml
        name: services

    - name: Install Traefik Environment File
      ansible.builtin.template:
        src: files/traefik/traefik.env.j2
        dest: /etc/traefik/env
        mode: "644"
      notify: Restart Traefik

    - name: Install Pocket ID Environment file
      ansible.builtin.template:
        src: files/traefik/pocketid.env.j2
        dest: /etc/pocketid/env
        mode: "644"

    - name: Template Main Config
      ansible.builtin.template:
        src: files/traefik/traefik.toml.j2
        dest: /etc/traefik/traefik.toml
        mode: "644"
      notify: Restart Traefik

    - name: Template conf.d
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/traefik/conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: "644"
      with_fileglob:
        - "files/traefik/conf.d/*.toml.j2"
      notify: Restart Traefik

  handlers:
    - name: Restart Traefik
      ansible.builtin.service:
        name: traefik
        state: restarted
        enabled: true

    - name: Restart Pocket ID
      ansible.builtin.service:
        name: pocketid
        state: restarted
        enabled: true
