[env]
EDITOR = "code --wait"
LIBVIRT_DEFAULT_URI = "qemu:///system"

[tools]
"pipx:ansible" = { version = "latest", uvx = "false", pipx_args = "--include-deps --preinstall netaddr --preinstall jmespath" }
"pipx:ansible-dev-tools" = { version = "latest", uvx = "false" }
"pipx:ansible-lint" = { version = "latest", uvx = "false" }

[tasks.vars]
alias = "vars"
description = "Lists all host vars"
run = "ansible -m setup {{arg(name='host_name')}}"


[tasks.playbook]
description = "Shortcut for running a select playbook"
run = "ansible-playbook {{arg(name='file')}}"
alias = ["p", "play"]

[tasks.edit]
description = "Edits a vault using VSCode"
run = "ansible-vault edit {{arg(name='file')}}"
alias = ["e"]
