---
collections:
  - name: community.general
  - name: community.docker
  - name: grafana.grafana
  - name: prometheus.prometheus

roles:
  - name: geerlingguy.docker
    version: 7.5.3
  - name: bpbradley.komodo
    version: abc90201b3127aff7eae8866281fd9be1ae8591f
