---
collections:
  - name: community.general
  - name: community.docker
  - name: grafana.grafana
  - name: prometheus.prometheus

roles:
  - name: geerlingguy.docker
    version: 7.5.3
  - name: bpbradley.komodo
    version: 0d24117d0d4a1a3e2f4caf445ee3c31e9e6c2095
