---
dumbdocker:
  hosts:
    dumbdocker.host.buckydev.com:
      ansible_host: 192.168.1.134

mchost:
  hosts:
    mchost.host.buckydev.com:
      ansible_host: 192.168.1.128

librenms:
  hosts:
    librenms.host.buckydev.com:
      ansible_host: 192.168.1.131

all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: keys/ansiblekey

docker:
  children:
    dumbdocker:
debian_vm:
  children:
    mchost:
    dumbdocker:
