---
mchost:
  hosts:
    mchost.host.buckydev.com:
      ansible_host: 192.168.1.128

nas:
  hosts:
    nas.host.buckydev.com:
      ansible_host: 192.168.1.129

librenms:
  hosts:
    librenms.host.buckydev.com:
      ansible_host: 192.168.1.131

dev2:
  hosts:
    dev2.host.buckydev.com:
      ansible_host: 192.168.1.132

dumbdocker:
  hosts:
    dumbdocker.host.buckydev.com:
      ansible_host: 192.168.1.134

metrics:
  hosts:
    metrics.host.buckydev.com:

komodo:
  hosts:
    komodo.host.buckydev.com:
