---
debian:
  children:
    # LXC
    proxy:
    quartz:
    homepage:
    pihole_lxc:
    tailscale:
    cloudflared:
    ntfy:
    timescale_ot:
    grafana_ot:
    shlink:
    # VM
    mchost:
    dumbdocker:
  vars:
    ansible_python_interpreter: /usr/bin/python3

ubuntu:
  children:
    librenms:
  vars:
    ansible_python_interpreter: /usr/bin/python3

alpine:
  children:
    # LXC
    vaultwarden:
    ddns:
  vars:
    ansible_python_interpreter: /usr/bin/python3

snmpd:
  children:
    librenms:
    mchost:
    dumbdocker:
    nas:
    dev2:
    pve:

docker:
  children:
    dumbdocker:

periphery:
  children:
    # media:
    komodo:

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

vagrant:
  children:
    karakeep:
    metrics:
    copyparty:
    komodo:
  vars:
    ansible_host: 192.168.121.10
    ansible_ssh_private_key_file: .vagrant/machines/default/libvirt/private_key
    ansible_user: vagrant
    ansible_become: true
    ansible_become_user: root
    ansible_become_method: sudo
