---
debian:
  children:
    # LXC
    proxy:
    quartz:
    homepage:
    pihole_lxc:
    tailscale:
    cloudflared:
    ntfy:
    timescale_ot:
    grafana_ot:
    shlink:
    # VM
    mchost:
    dumbdocker:
  vars:
    ansible_python_interpreter: /usr/bin/python3

ubuntu:
  children:
    librenms:
  vars:
    ansible_python_interpreter: /usr/bin/python3

alpine:
  children:
    # LXC
    vaultwarden:
    ddns:
  vars:
    ansible_python_interpreter: /usr/bin/python3

snmpd:
  children:
    librenms:
    mchost:
    dumbdocker:
    nas:
    dev2:

docker:
  children:
    dumbdocker:

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
