komodo_core_webhook_secret: "{{ vault_komodo_core_webhook_secret }}"
komodo_core_jwt_secret: "{{ vault_komodo_core_jwt_secret }}"

komodo_db_username: "admin"
komodo_db_password: "{{ vault_komodo_db_password }}"
