alloy_config: |
  prometheus.remote_write "remote" {
    endpoint {
      url = "http://{{ hostvars['metrics.host.buckydev.com']['ansible_host'] }}:9090/api/v1/write"
    }
  }

  prometheus.exporter.unix "node" { }

  prometheus.scrape "unix_scrape" {
    targets = prometheus.exporter.unix.node.targets
    forward_to = [prometheus.remote_write.remote.receiver]
  }
