# Grafana
grafana_ini:
  security:
    admin_user: root
    admin_password: "{{ vault_grafana_admin_password }}"

  server:
    domain: "metrics.host.buckydev.com"

grafana_datasources:
  - name: metrics
    type: prometheus
    url: "http://localhost:9090"

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 41
    datasource: metrics

# Prometheus
prometheus_storage_retention: "90d"
prometheus_config_flags_extra:
  web.enable-remote-write-receiver: ""

# Alloy
alloy_env_file_vars:
  CONFIG_FILE: /etc/alloy/conf.alloy
  CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:12345 --stability.level=public-preview --feature.community-components.enabled=true"
