---
- name: Debian-family System Upgrade
  ansible.builtin.apt:
    upgrade: "{{ sysupgrade_debian_upgrade }}"
    autoclean: "{{ sysupgrade_debian_autoclean }}"
    autoremove: "{{ sysupgrade_debian_autoremove }}"
    update_cache: "{{ sysupgrade_debian_update_cache }}"
