- name: Alpine-family System Upgrade
  import_tasks: alpine.yaml
  when: ansible_facts['os_family']|lower == 'alpine'

- name: Debian-family System Upgrade
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'
