jellystack:
  - service: jellyfin
    rule: "Host(`jellyfin.{{ traefik_local_domain }}`)"
    url: "http://192.168.0.11:8096"
    middlewares:
      - jellyfin-mw

  - service: jellyseer
    rule: "Host(`jellyseer.{{ traefik_local_domain }}`) || Host(`jellyseer.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:5055"
    middlewares:

  - service: homarr
    rule: "Host(`home.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:7575"
    middlewares:

  - service: qbitt
    rule: "Host(`qbitt.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:8080"
    middlewares:

  - service: radarr
    rule: "Host(`rad.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:7878"
    middlewares:

  - service: sonarr
    rule: "Host(`son.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:8989"
    middlewares:

  - service: prowlarr
    rule: "Host(`prowl.arr.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:9696"
    middlewares:

local:
  - service: auth
    rule: "Host(`auth.{{ traefik_root_domain }}`)"
    url: "http://localhost:1411"
    middlewares:

  - service: mealie
    rule: "Host(`mealie.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.134:9225"
    middlewares:

  - service: hoarder
    rule: "Host(`hoarder.{{ traefik_local_domain }}`) || Host(`karakeep.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.14:3000"
    middlewares:

  - service: pihole-lxc
    rule: "Host(`pihole.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.3:80"
    middlewares:
      # - pihole-redirect

  - service: pihole-2
    rule: "Host(`pihole-2.{{ traefik_local_domain }}`)"
    url: "http://192.168.0.3:80"
    middlewares:
      # - pihole-redirect

  - service: ddns
    rule: "Host(`ddns.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.8:8000"
    middlewares:

  - service: dockage
    rule: "Host(`dockage.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.128:5001"
    middlewares:

  - service: hass
    rule: "Host(`hass.{{ traefik_local_domain }}`)"
    url: "http://192.168.0.10:8123"
    middlewares:

  - service: ntfy
    rule: "Host(`ntfy.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.5:80"
    middlewares:

  - service: portainer
    rule: "Host(`portainer.{{ traefik_local_domain }}`)"
    url: "https://192.168.0.239:9443"
    middlewares:

  - service: pve
    rule: "Host(`pve.{{ traefik_local_domain }}`)"
    url: "https://192.168.0.189:8006"
    middlewares:

  - service: quartz
    rule: "Host(`quartz.{{ traefik_local_domain }}`)"
    url: "http://192.168.1.7:80"
    middlewares:

  - service: immich
    rule: "Host(`immich.{{ traefik_local_domain }}`)"
    url: "http://192.168.0.11:2283"
    middlewares:

external:
  - service: jellyfin-external
    rule: "Host(`watch.{{ traefik_root_domain }}`)"
    url: "http://192.168.0.11:8096" # Public jellyfin port = 8196; unused due to issues
    middlewares:
      - jellyfin-mw
